name: "check frontend js/css bundle size"
on:
  push:
    branches:
    tags:
    paths:
      - "hugo/**/*.jsx?"
      - "hugo/**/*.tsx?"
      - "hugo/**/*.scss"
  pull_request:
    paths:
      - "hugo/**/*.jsx?"
      - "hugo/**/*.tsx?"
      - "hugo/**/*.scss"

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: hugo/
          build_script: prod
